export type RecordElevationSemantic = {
	none: string;
	level1: string;
	level2: string;
	level3: string;
	level4: string;
	level5: string;
	focus: string;
	focusStrong: string;
	accent: string;
	accentStrong: string;
	overlay: string;
	modal: string;
	star: string;
	icon: string;
	pill: string;
	card: string;
	cardHover: string;
	detail: string;
	focusNode: string;
	fullscreen: string;
};
