import type { TokenThemeMode } from '$stylist/theme/type/alias/theme-mode';
import type { ObjectThemeTypography } from '$stylist/theme/type/object/typography';

export type Theme = {
	mode: TokenThemeMode;
	colors: {
		primary: Record<number, string>;
		secondary: Record<number, string>;
		tertiary?: Record<number, string>;
		neutral: Record<number, string>;
		success: Record<number, string>;
		info: Record<number, string>;
		warning: Record<number, string>;
		error: Record<number, string>;
		danger: Record<number, string>;
		background: {
			primary: string;
			secondary: string;
			tertiary: string;
			default: string;
			subtle: string;
			raised: string;
			floating: string;
			container: string;
			containerLow: string;
			containerHigh: string;
			transparent: string;
			inverse: string;
		};
		text: {
			primary: string;
			secondary: string;
			tertiary: string;
			default: string;
			inverse: string;
			onAccent: string;
			link: string;
		};
		border: {
			primary: string;
			secondary: string;
			tertiary: string;
			default: string;
			inverse: string;
			accent: string;
		};
		surfaceTint?: {
			level1: string;
			level2: string;
			level3: string;
			level4: string;
			level5: string;
		};
		onPrimary?: string;
		onSecondary?: string;
		onTertiary?: string;
		onSuccess?: string;
		onInfo?: string;
		onWarning?: string;
		onError?: string;
		onBackground?: string;
		onSurface?: string;
		onSurfaceContainer?: string;
		primaryContainer?: string;
		onPrimaryContainer?: string;
		secondaryContainer?: string;
		onSecondaryContainer?: string;
		tertiaryContainer?: string;
		onTertiaryContainer?: string;
		errorContainer?: string;
		onErrorContainer?: string;
		successContainer?: string;
		onSuccessContainer?: string;
		warningContainer?: string;
		onWarningContainer?: string;
		outline?: string;
		outlineVariant?: string;
		outlineDefault?: string;
		outlineSubtle?: string;
		outlineStrong?: string;
		shadow?: string;
		scrim?: string;
		backdrop?: string;
	};
	typography: ObjectThemeTypography;
};
