import type { RecordColorScale } from '$stylist/theme/type/record/color-scale';
import type { ThemeColorBackground } from '$stylist/theme/type/struct/theme-color-background';
import type { ThemeColorBorder } from '$stylist/theme/type/struct/theme-color-border';
import type { ThemeColorSurfaceTint } from '$stylist/theme/type/struct/theme-color-surface-tint';
import type { ThemeColorText } from '$stylist/theme/type/struct/theme-color-text';

export type ThemeColors = {
	primary: RecordColorScale;
	secondary: RecordColorScale;
	tertiary?: RecordColorScale;
	neutral: RecordColorScale;
	success: RecordColorScale;
	info: RecordColorScale;
	warning: RecordColorScale;
	error: RecordColorScale;
	danger: RecordColorScale;
	background: ThemeColorBackground;
	text: ThemeColorText;
	border: ThemeColorBorder;
	surfaceTint?: ThemeColorSurfaceTint;
	onPrimary?: string;
	onSecondary?: string;
	onTertiary?: string;
	onSuccess?: string;
	onInfo?: string;
	onWarning?: string;
	onError?: string;
	onBackground?: string;
	onSurface?: string;
	onSurfaceContainer?: string;
	primaryContainer?: string;
	onPrimaryContainer?: string;
	secondaryContainer?: string;
	onSecondaryContainer?: string;
	tertiaryContainer?: string;
	onTertiaryContainer?: string;
	errorContainer?: string;
	onErrorContainer?: string;
	successContainer?: string;
	onSuccessContainer?: string;
	warningContainer?: string;
	onWarningContainer?: string;
	outline?: string;
	outlineVariant?: string;
	outlineDefault?: string;
	outlineSubtle?: string;
	outlineStrong?: string;
	shadow?: string;
	scrim?: string;
	backdrop?: string;
};
