import type { ThemeColorBackground } from '$stylist/theme/type/object/theme-color-background';
import type { ThemeColorBorder } from '$stylist/theme/type/object/theme-color-border';
import type { ThemeColorSurfaceTint } from '$stylist/theme/type/object/theme-color-surface-tint';
import type { ThemeColorText } from '$stylist/theme/type/object/theme-color-text';

export type ThemeColors = {
	primary: Record<number, string>;
	secondary: Record<number, string>;
	tertiary?: Record<number, string>;
	neutral: Record<number, string>;
	success: Record<number, string>;
	info: Record<number, string>;
	warning: Record<number, string>;
	error: Record<number, string>;
	danger: Record<number, string>;
	background: ThemeColorBackground;
	text: ThemeColorText;
	border: ThemeColorBorder;
	surfaceTint?: ThemeColorSurfaceTint;
	onPrimary?: string;
	onSecondary?: string;
	onTertiary?: string;
	onSuccess?: string;
	onInfo?: string;
	onWarning?: string;
	onError?: string;
	onBackground?: string;
	onSurface?: string;
	onSurfaceContainer?: string;
	primaryContainer?: string;
	onPrimaryContainer?: string;
	secondaryContainer?: string;
	onSecondaryContainer?: string;
	tertiaryContainer?: string;
	onTertiaryContainer?: string;
	errorContainer?: string;
	onErrorContainer?: string;
	successContainer?: string;
	onSuccessContainer?: string;
	warningContainer?: string;
	onWarningContainer?: string;
	outline?: string;
	outlineVariant?: string;
	outlineDefault?: string;
	outlineSubtle?: string;
	outlineStrong?: string;
	shadow?: string;
	scrim?: string;
	backdrop?: string;
};
